### PR TITLE
TrackWishlist in Loot feature

### LINKED ISSUE #337: loadwl - Wishlist command
First of all, let me say.... nice work on this whole thing.
When i start the game and alter my wishlist and then go in a raid and use the "loadwl" command.. it loads the "old" wishlist.
After raid i alter the wishlist again.. go in raid.. use "untrack *" command and all tracks disapear. 
Then using "loadwl" again and it loads the very first wishlist from since when i startet the game, plus what i added to it. but it dont untrack things i deleted from wishlist. So i can only add things but not delete?
Am i doing it wrong? or this a bug?

### PR DESCRIPTION
**Pull request by solareon**
Removed loadwl command as we have now incorporated it into an option under the Loot feature. If the option is on we assign the Wishlist variable to the wishlist class G2903 or null as appropriate. Then when performing checks in TryAddRecordIfTracked() we shortcut if the item was found in the tracklist or if the Wishlist is null.

Wasn't sure if Wishlist should be private or not. Feel free to change if needed.

Fixes #337

### CODE REVIEW

File: Features/LootItems.cs [hunk 1]
```diff
@@ -35,9 +36,14 @@ internal class LootItems : PointOfInterests
 		[ConfigurationProperty]
 		public bool ShowPrices { get; set; } = true;
 
+		[ConfigurationProperty]
+		public bool TrackWishlist { get; set; } = true;
+
 		public override float CacheTimeInSec { get; set; } = 3f;
 		public override Color GroupingColor => Color;
 
+		public GClass2903? Wishlist { get; set; } = null;
```
Comment (sailro) [inline Features/LootItems.cs:45]: This will break the compilation next update. We should never reference a GClassXXXX type, they are auto numbered by the deobfuscator.

Comment (solareon) [reply Features/LootItems.cs:45]: That makes sense. What would be a good method to define that Wishlist variable?

Comment (sailro) [reply Features/LootItems.cs:45]: Given we are in `RefreshData`, it's ok to retrieve the instance every call. Let me write that down.

Comment (solareon) [reply Features/LootItems.cs:45]: Got it. I tried also doing something like this but my spidey sense says that's not a good. Should I move it back down to both the TryAddRecordIfTracked and place it also in the Commands.cs?

```cs
public object? Wishlist { get; set; } = null;```

Comment (solareon) [reply Features/LootItems.cs]: Good copy. Let me take a look.

**Comment by solareon** [comment]
Refactor works perfect.

**Comment by sailro** [comment]
Okay, let's merge this one. It will be more convenient indeed.
